
format = """\
[\uE0B6](fg:red     bg:none  )$username\
[\uE0B4](fg:red     bg:green )$hostname\
[\uE0B4](fg:green   bg:yellow)$directory\
[\uE0B4](fg:yellow  bg:blue  )$git_branch$git_status\
[\uE0B4](fg:blue    bg:purple)\
$nodejs\
[\uE0B4](fg:purple  bg:cyan  )\
[\uE0B4](fg:cyan    bg:none)\
$line_break\
$jobs$character"""
# [\uE0B4](fg:#E5C07B bg:#61AFEF)$spack\
# [\uE0B4](fg:#3A95C7 bg:#C678DD)$time\

add_newline = false

[character]
# format = ""
success_symbol            = "[\uf054](bold green)"
error_symbol              = "[\uf054](bold red)"
vicmd_symbol              = "[\uf054](bold yellow)"
# vimcmd_replace_one_symbol = "[\uf054](bold yellow)"
# vimcmd_replace_symbol     = "[\uf054](bold yellow)"
# vimcmd_visual_symbol      = "[\uf054](bold yellow)"
# disabled                  = false

[username]
style_user  = "fg:black bg:red"
style_root  = "fg:black bg:red"
format      = "[\uf007 $user]($style)"
show_always = true
disabled    = false

[hostname]
ssh_only   = false
ssh_symbol = "\uf953"
trim_at    = "."
format     = "[ $ssh_symbol$hostname ]($style)"
style      = "fg:black bg:green"
disabled   = false

[directory]
truncation_length = 3
truncate_to_repo  = true
format            = "[ \uf413  $path]($style)"
style             = "fg:black bg:yellow"
disabled          = false
read_only         = "\uf023"
# read_only_style = ""
truncation_symbol = "…/"
# repo_root_style = ""
# repo_root_format = ""
# home_symbol = ""
# use_os_oath_sep = ""
[directory.substitutions]
"Desktop"   = "\uf108 "
"Documents" = "\uf718 "
"Downloads" = "\uf019 "
"Mail"      = "\uf5ed "
"Music"     = "\ufc58 "
"Pictures"  = "\uf03e "
"Videos"    = "\ufa66 "
"Projects"  = "\ue601 "
"Public"    = "\uf093 "
"Share"     = "\uf995 "
"GitHub"    = "\uf7a3 "
"dotfiles"  = "\ue615 "
"Important" = "\uf1cd "

[git_branch]
# always_show_remote = false
format = "[ $symbol $branch]($style)"
symbol = "\ue702"
style  = "fg:black bg:blue"
# truncation_length = 2^63 - 1
# truncation_symbol = "…"
# only_attached = false
# ignore_branches = []
# disabled = false

[git_status]
format     = "[ $all_status$ahead_behind]($style)"
style      = "fg:black bg:blue"
conflicted = "\uf071 ${count}"
# ahead = "🏎💨"
# behind = "😰"
# diverged = "😵"
up_to_date = ""# "\uf00c"# "✓"
untracked  = "\ue0b5 \ufbae ${count} "#"🤷"
stashed    = "\ue0b5 \uf487 ${count} "#"📦"
modified   = "\ue0b5 \uf459 ${count} "#"📝"
staged     = "\ue0b5 \uf457 ${count} "#" [++($count)](green)"
renamed    = "\ue0b5 \uf954 ${count} "#"👅"
deleted    = "\ue0b5 \uf6bf ${count} "#"🗑":"
ahead      = "\ue0b5 \uf093 ${count} "#"⇡${count}"
behind     = "\ue0b5 \uf019 ${count} "#"⇣${count}"
diverged   = "\ue0b5 \uf093 ${ahead_count} \uf019 ${behind_count} "#"⇕⇡${ahead_count}⇣${behind_count}"

[cmd_duration]
min_time = 500
format   = "time [$duration](bold yellow)"

[time]
format      = "[ $time ]($style)"
# use_12hr = false
time_format = "%T"
style       = "fg:#282C34 bg:#C678DD"
# utc_time_offset = "local"
disabled    = true
# time_range = "-"

[nodejs]
format   = "[ $symbol$version]($style)"
# version_format = ""
symbol   = "\uf898 "
# detect_extensions = []
# detect_files = []
# detect_folders = []
style    = "fg:#282C34 bg:#61AFEF"
disabled = false
# not_capable_style = "bold red"

[spack]
# truncation_length = 1
symbol   = "\uf28a "
style    = "fg:#282C34 bg:#61AFEF"
format   = "[$symbol$environment]($style)"
disabled = false

# format = """
# [](#9A348E)\
# $username\
# [](bg:#DA627D fg:#9A348E)\
# $directory\
# [](fg:#DA627D bg:#FCA17D)\
# $git_branch\
# $git_status\
# [](fg:#FCA17D bg:#86BBD8)\
# $c\
# $elixir\
# $elm\
# $golang\
# $haskell\
# $java\
# $julia\
# $nodejs\
# $nim\
# $rust\
# [](fg:#86BBD8 bg:#06969A)\
# $docker_context\
# [](fg:#06969A bg:#33658A)\
# $time\
# [ ](fg:#33658A)\
# """

# # Disable the blank line at the start of the prompt
# # add_newline = false
#
# # You can also replace your username with a neat symbol like  to save some space
# [username]
# show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
# format = '[$user ]($style)'
#
# [directory]
# style = "bg:#DA627D"
# format = "[ $path ]($style)"
# truncation_length = 3
# truncation_symbol = "…/"
#
# # Here is how you can shorten some long paths by text replacement
# # similar to mapped_locations in Oh My Posh:
# [directory.substitutions]
# "Documents" = " "
# "Downloads" = " "
# "Music" = " "
# "Pictures" = " "
# # Keep in mind that the order matters. For example:
# # "Important Documents" = "  "
# # will not be replaced, because "Documents" was already substituted before.
# # So either put "Important Documents" before "Documents" or use the substituted version:
# # "Important  " = "  "
#
# [c]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [docker_context]
# symbol = " "
# style = "bg:#06969A"
# format = '[[ $symbol $context ](bg:#06969A)]($style) $path'
#
# [elixir]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [elm]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [git_branch]
# symbol = ""
# style = "bg:#FCA17D"
# format = '[[ $symbol $branch ](bg:#FCA17D)]($style)'
#
# [git_status]
# style = "bg:#FCA17D"
# format = '[[($all_status$ahead_behind )](bg:#FCA17D)]($style)'
#
# [golang]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [haskell]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [java]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [julia]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [nodejs]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [nim]
# symbol = " "
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [rust]
# symbol = ""
# style = "bg:#86BBD8"
# format = '[[ $symbol ($version) ](bg:#86BBD8)]($style)'
#
# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#33658A"
# format = '[[ ♥ $time ](bg:#33658A)]($style)'


# add_newline = false
# scan_timeout = 30
# command_timeout = 700
# format = "$all"
# # format = """
# # $directory\
# # $git_branch\
# # $git_commit\
# # $git_state\
# # $git_status\
# # $line_break\
# # $character
# # """
#
# [character]
# success_symbol = "[\uf054](bold green)"
# error_symbol = "[\uf054](bold red)"
# vicmd_symbol = "[\uf054](bold yellow)"
#
# [username]
# style_user = "green"
# style_root = "red"
# format = "[\uf007 $user]($style)[@](purple)"
# disabled = false
# show_always = true
#
# [hostname]
# ssh_only = false
# style = "blue"
# format =  "[$hostname]($style) "
# trim_at = "."
# disabled = false
#
# [directory]
# truncation_length = 100
# truncate_to_repo = false
# format = "[\uf413 $symbol$path ]($style)"
# style = "bright-cyan"
#
# #[aws]
# #format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
# #
# #[cmake]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[cmd_duration]
# #format = '\[[⏱ $duration ]($style)\]'
# #
# #[cobol]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[conda]
# #format = '\[[$symbol$environment]($style)\]'
# #
# #[crystal]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[dart]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[deno]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[docker_context]
# #format = '\[[$symbol$context]($style)\]'
# #
# #[dotnet]
# #format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'
# #
# #[elixir]
# #format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'
# #
# #[elm]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[erlang]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[gcloud]
# #format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'
# #
# [git_commit]
# disabled = true
#
# [git_state]
# disabled = true
#
# [git_metrics]
# added_style = "blue"
# deleted_style = "red"
# format = '[+$added]($added_style)/[-$deleted]($deleted_style)\] '
# #disabled = false
#
# [git_branch]
# symbol = "\uf7a1 "
# format = '[$symbol$branch ]($style)'
# style = "bright-green"
#
# [git_status]
# format = '([- $all_status$ahead_behind]($style))'
# style = "bright-red"
# conflicted = "[\ue728 ](red)"
# ahead      = "[\uf062 ${count} ](green)"
# behind     = "[\uf063 ${count} ](green)"
# diverged   = "${ahead_count} ${behind_count}"
# untracked  = "[\uf128 ${count} ](red)"
# stashed    = "[\uf44e ](blue)"
# modified   = "[\uf044 ${count} ](yellow)"
# staged     = "[\uf067 ${count} ](blue)"
# renamed    = "[\uf954 ${count} ](yellow)"
# deleted    = "[\uf655 ${count} ](red)"
# #
# #[golang]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[helm]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[hg_branch]
# #format = '\[[$symbol$branch]($style)\]'
# #
# #[java]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[julia]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[kotlin]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[kubernetes]
# #format = '\[[$symbol$context( \($namespace\))]($style)\]'
# #
# #[lua]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[memory_usage]
# #format = '\[$symbol[$ram( | $swap)]($style)\]'
# #
# #[nim]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[nix_shell]
# #format = '\[[$symbol$state( \($name\))]($style)\]'
# #
# #[nodejs]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[ocaml]
# #format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'
# #
# #[openstack]
# #format = '\[[$symbol$cloud(\($project\))]($style)\]'
# #
# #[package]
# #format = '\[[$symbol$version]($style)\]'
# #
# #[perl]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[php]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[pulumi]
# #format = '\[[$symbol$stack]($style)\]'
# #
# #[purescript]
# #format = '\[[$symbol($version)]($style)\]'
# #
# [python]
# format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\)) ]($style)'
# symbol = "\ue235 "
# #
# #[red]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[ruby]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[rust]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[scala]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[sudo]
# #format = '\[[as $symbol]\]'
# #
# #[swift]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[terraform]
# #format = '\[[$symbol$workspace]($style)\]'
# #
# #[time]
# #format = '\[[$time]($style)\]'
# #
# #[username]
# #format = '\[[$user]($style)\]'
# #
# #[vagrant]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[vlang]
# #format = '\[[$symbol($version)]($style)\]'
# #
# #[zig]
# #format = '\[[$symbol($version)]($style)\]'
#
#
#
