#!/usr/bin/env bash

##
## TeX Live
## 
## URL: https://tug.org/texlive/
##

export HOSTNAME=$(hostname -s)
export STOW_HOME=$HOME/.local/xstow/$HOSTNAME
export VERSION="2022"

### Remove
#rm -rfv   $STOW_HOME/{tmp,src,pkg}/texlive
#mkdir -pv $STOW_HOME/{tmp,src,pkg}/texlive
#
#
### Download
#cd        $STOW_HOME/tmp/texlive
#echo "PWD: $(pwd)"
#wget --no-check-certificate https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
#wget --no-check-certificate https://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz.sha256
#
### Extract
#cd        $STOW_HOME/src/texlive
#echo "PWD: $(pwd)"
#tar -xvf  $STOW_HOME/tmp/texlive/install-tl-unx.tar.gz

## Generate Profile
cd        $STOW_HOME/src/texlive/install-tl-*
echo "PWD: $(pwd)"
rm -rfv texlive.profile 
echo "# Generated by k5-mot" > texlive.profile
sed -i -e "\$a \
TEXDIR         $STOW_HOME/pkg/texlive-$VERSION                  \n\
TEXMFSYSVAR    $STOW_HOME/pkg/texlive-$VERSION/texmf-sysvar     \n\
TEXMFSYSCONFIG $STOW_HOME/pkg/texlive-$VERSION/texmf-sysconfig  \n\
TEXMFLOCAL     $STOW_HOME/pkg/texlive-$VERSION/texmf-local      \n\
TEXMFHOME      $STOW_HOME/pkg/texlive-$VERSION/texmf            \n\
TEXMFVAR       $STOW_HOME/pkg/texlive-$VERSION/texmf-var        \n\
TEXMFCONFIG    $STOW_HOME/pkg/texlive-$VERSION/texmf-config        " ./texlive.profile
sed -i -e "\$a \
selected_scheme scheme-custom           \n\
binary_x86_64-linux 1                   \n\
collection-basic 1                      \n\
collection-bibtexextra 1                \n\
collection-binextra 1                   \n\
collection-context 1                    \n\
collection-fontsextra 1                 \n\
collection-fontsrecommended 1           \n\
collection-fontutils 1                  \n\
collection-formatsextra 1               \n\
collection-games 1                      \n\
collection-humanities 1                 \n\
collection-langarabic 1                 \n\
collection-langchinese 1                \n\
collection-langcjk 1                    \n\
collection-langcyrillic 1               \n\
collection-langczechslovak 1            \n\
collection-langenglish 1                \n\
collection-langeuropean 1               \n\
collection-langfrench 1                 \n\
collection-langgerman 1                 \n\
collection-langgreek 1                  \n\
collection-langitalian 1                \n\
collection-langjapanese 1               \n\
collection-langkorean 1                 \n\
collection-langpolish 1                 \n\
collection-langportuguese 1             \n\
collection-langspanish 1                \n\
collection-latex 1                      \n\
collection-latexextra 1                 \n\
collection-latexrecommended 1           \n\
collection-luatex 1                     \n\
collection-mathscience 1                \n\
collection-metapost 1                   \n\
collection-music 1                      \n\
collection-pictures 1                   \n\
collection-plaingeneric 1               \n\
collection-pstricks 1                   \n\
collection-texworks 1                   \n\
collection-xetex 1                      \n\
instopt_adjustpath 0                    \n\
instopt_adjustrepo 1                    \n\
instopt_letter 0                        \n\
instopt_portable 0                      \n\
instopt_write18_restricted 1            \n\
tlpdbopt_autobackup 1                   \n\
tlpdbopt_backupdir tlpkg/backups        \n\
tlpdbopt_create_formats 1               \n\
tlpdbopt_desktop_integration 1          \n\
tlpdbopt_file_assocs 1                  \n\
tlpdbopt_generate_updmap 0              \n\
tlpdbopt_install_docfiles 1             \n\
tlpdbopt_install_srcfiles 1             \n\
tlpdbopt_post_code 1                    \n\
tlpdbopt_sys_bin /usr/local/bin         \n\
tlpdbopt_sys_info /usr/local/share/info \n\
tlpdbopt_sys_man /usr/local/share/man   \n\
tlpdbopt_w32_multi_user 1                  " ./texlive.profile

### Install
./install-tl --profile=./texlive.profile

#porg -lp  texlive-${VERSION} "./install-tl --profile=../texlive.profile"
#for file in $(find ${HOME}/.porg/${HOSTNAME}/opt/texlive/${VERSION}/bin/x86_64-linux/ -type f); do
#  porg -lp+ texlive-${VERSION} "ln -sfv $file ${HOME}/.porg/${HOSTNAME}/usr/bin"
#done
#for filelink in $(find ${HOME}/.porg/${HOSTNAME}/opt/texlive/${VERSION}/bin/x86_64-linux/ -type l); do
#  srcname=$(readlink -f $filelink)
#  dstname=${HOME}/.porg/${HOSTNAME}/usr/bin/$(basename $filelink)
#  porg -lp+ texlive-${VERSION} "ln -sfv $srcname $dstname"
#done
#
### Check
#porg texlive
#cd ${HOME}
#



## Install
cd $STOW_HOME/pkg/texlive-2022
echo "PWD: $(pwd)"
dirs=$(find . -type d)
for dir in $dirs; do 
    mkdir -pv $STOW_HOME/$dir
done
cd        $STOW_HOME/pkg
echo "PWD: $(pwd)"
xstow -v chrome 
if [ $? = 0 ]; then
    echo "Success $?"
else
    echo "Failed $?"
fi

## Check
cd $HOME

